### ISSUE TITLE
API returns 500 error when requests are within a few seconds

### ISSUE THREAD

**Issue by robinbb77** [mevdschee/php-crud-api#432]
Whenever I need to do 2 requests within a few seconds of each other, api.php returns a 500 internal server error with the following in my log files:

`PHP Fatal error: Uncaught TypeError: Argument 1 passed to Tqdev\PhpCrudApi\PathTree::__construct() must be an instance of Tqdev\PhpCrudApi\object or null, object given, called in D:\mysite\api\api.php on line 3838 and defined in D:\mysite\api\api.php:3776
Stack trace:
#0 D:\mysite\api\api.php(3838): Tqdev\PhpCrudApi\PathTree->__construct(Object(stdClass))
#1 D:\mysite\api\api.php(2703): Tqdev\PhpCrudApi\PathTree::fromJson(Object(stdClass))
#2 D:\mysite\api\api.php(2694): Tqdev\PhpCrudApi\SimpleRouter->loadPathTree()
#3 D:\mysite\api\api.php(4254): Tqdev\PhpCrudApi\SimpleRouter->__construct(Object(Tqdev\PhpCrudApi\Responder), Object(Tqdev\PhpCrudApi\TempFileCache), 10)
#4 D:\mysite\api\api. in D:\mysite\api\api.php on line 3776`

When there is an apprioprate time inbetween requests it all seems to work fine.

Any fixes?

**Comment by mevdschee** [comment]
This has to do with the cache. Did you configure any cache? If so, which one? Try "NoCache" and see if the problem disappears. It probably is a file permission problem in your system's tmp directory.

**Comment by mevdschee** [comment]
any update?

**Comment by robinbb77** [comment]
Hi, did not have the time to look at it, will keep you updated as soon as I get to it.

For now, PHP-version is 7.1.22 and my server is hosted by an external hosting company.

When I have the time, I will try testing it locally and try to disable cache. As far as I know, I have not configured a cache, but I think the hosting company has by default.

**Comment by mevdschee** [comment]
Okay, so probably it is write permission error in the cache folder. Try this config parameter:

    'cacheType' => 'NoCache',

under the 'database' config parameter.

**Comment by mevdschee** [comment]
Any update?

**Comment by mevdschee** [comment]
Closing due to inactivity.
