### ISSUE TITLE
Help with DB settings on initial setup

### ISSUE THREAD

**Issue by BataBoom** [mevdschee/php-crud-api#866]
```
 All configuration options are also available as environment variables. Write the config option with capitals, a "PHP_CRUD_API_" prefix and underscores for word breakes, so for instance:

    PHP_CRUD_API_DRIVER=mysql
    PHP_CRUD_API_ADDRESS=localhost
    PHP_CRUD_API_PORT=3306
    PHP_CRUD_API_DATABASE=php-crud-api
    PHP_CRUD_API_USERNAME=php-crud-api
    PHP_CRUD_API_PASSWORD=php-crud-api
    PHP_CRUD_API_DEBUG=1

The environment variables take precedence over the PHP configuration.
```

First time setting up so could be wrong but README.md says the config file is the bottom of api.php in the root directory. Though switching off the default db details doesn't work. dbname/user/pass. 

Specs:
Nginx 1.21.4
php 7.4.3
mysql 8.0.28

Error message prob won't help but I'll leave it anyways. 

```
> PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'php-crud-api'@'localhost' (using password: YES) in /var/www/boom/php-crud-api/api.include.php:6555
> Stack trace:
> #0 /var/www/boom/php-crud-api/api.include.php(6555): PDO->__construct()
> #1 /var/www/boom/php-crud-api/api.include.php(6620): Tqdev\PhpCrudApi\Da                                                             tabase\LazyPdo->pdo()
> #2 /var/www/boom/php-crud-api/test.php(163): Tqdev\PhpCrudApi\Database\L                                                             azyPdo->errorInfo()
> #3 /var/www/boom/php-crud-api/test.php(188): loadFixture()
> #4 /var/www/boom/php-crud-api/test.php(201): run()
> #5 {main}
>   thrown in /var/www/boom/php-crud-api/api.include.php on line 6555
```

If anyone knows whats up kindly let me know. Up and running using 'php-crud-api' for all db credentials for now.

**Comment by mevdschee** [comment]
You don't need to use environment variables, that is optional. Adjust the config at the bottom of api.php and you are done.

**Comment by awinante** [comment]
What if you are using the api.include.php instead? There is no config at the bottom of the file? Is there an example of how to setup api.include.php?
